[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/*"]

[workspace.package]
edition = "2024"
authors = ["Ali Samji <ali@ybor.ai>"]
license-file = "LICENSE"
repository = "https://github.com/ali-ybor/dummy"

[workspace.dependencies]
