name: 'Sync Helm Chart appVersion'
description: 'Syncs Helm chart appVersion with the app version from release-please manifest'
inputs:
  chart-path:
    description: 'Path to the Helm chart directory'
    required: true
  app-path:
    description: 'Path to the app in release-please manifest'
    required: true
  release-please-outputs:
    description: 'JSON string of release-please step outputs'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - name: Debug Me
      shell: bash
      env:
        RELEASE_PLEASE_OUTPUTS: ${{ inputs.release-please-outputs }}
        PR_CREATED: ${{ fromJSON(inputs.release-please-outputs).prs_created || fromJSON(inputs.release-please-outputs).pr_created }}
      run: env
    # TODO: Force Publish Helm off of the current branch.
    # - name: Checkout PR branch
    #   if: ${{ fromJSON(inputs.release-please-outputs).prs_created || fromJSON(inputs.release-please-outputs).pr_created }}
    #   uses: actions/checkout@v4
    #   with:
    #     ref: ${{ fromJSON(fromJSON(inputs.release-please-outputs).pr || '{}').headBranchName }}
    #     path: pr-workspace
    # - name: Sync Helm Version
    #   if: ${{ fromJSON(inputs.release-please-outputs).prs_created || fromJSON(inputs.release-please-outputs).pr_created }}
    #   shell: bash
    #   working-directory: pr-workspace
    #   env:
    #     CHART_PATH: ${{ inputs.chart-path }}
    #     APP_PATH: ${{ inputs.app-path }}
    #     HEAD_BRANCH: ${{ fromJSON(fromJSON(inputs.release-please-outputs).pr || '{}').headBranchName }}
    #     BASE_BRANCH: ${{ fromJSON(fromJSON(inputs.release-please-outputs).pr || '{}').baseBranchName }}
    #     GH_TOKEN: ${{ inputs.github-token }}
    #   run: ${{ github.action_path }}/sync-helm-version.sh
