name: Release Please
# Dummy
on:
  push:
    branches:
      - main

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    name: Create Release or Bump Version
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    outputs:
      release_created: ${{ steps.release-please.outputs.releases_created || steps.release-please.outputs.release_created }}
      pr_created: ${{ steps.release-please.outputs.prs_created || steps.release-please.outputs.pr_created }}
      pr: ${{ steps.release-please.outputs.pr || '{}' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run release-please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ github.token }}
      # TODO: Force Publish Helm

# github.event.repository.default_branch
  helmVersionHack:
    name: Sync Helm appVersion
    runs-on: ubuntu-latest

    needs:
      - release-please

    if: needs.release-please.outputs.pr_created == 'true'

    permissions:
      contents: write

    env:
      CHART_PATH: helm/hello-world
      APP_PATH: crates/hello-world
      HEAD_BRANCH: ${{ fromJSON(needs.release-please.outputs.pr).headBranchName }}
      BASE_BRANCH: ${{ fromJSON(needs.release-please.outputs.pr).baseBranchName }}
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ fromJSON(needs.release-please.outputs.pr).headBranchName }}
      - name: Sync App Version
        uses: ./.github/release-please-helm-sync-action
        with:
          chart-path: ${{ env.CHART_PATH }}
          app-path: ${{ env.APP_PATH }}
          head-branch: ${{ env.HEAD_BRANCH }}
          base-branch: ${{ env.BASE_BRANCH }}
