name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Create Release or Bump Version
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    concurrency:
      group: release-please-${{ github.ref }}
      cancel-in-progress: false

    outputs:
      release_created: ${{ steps.release-please.outputs.releases_created || steps.release-please.outputs.release_created }}
      pr_created: ${{ steps.release-please.outputs.prs_created || steps.release-please.outputs.pr_created }}
      version: ${{ steps.release-please.outputs['crates/hello-world--version'] }}
      helmVersion: ${{ steps.release-please.outputs['helm/hello-world--version'] }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run release-please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ github.token }}
      - run: |
          echo '${{ toJSON(steps.release-please.outputs) }}'
