name: Release Please
# Dummy
on:
  push:
    branches:
      - main

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    name: Create Release or Bump Version
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    outputs:
      release_created: ${{ steps.release-please.outputs.releases_created || steps.release-please.outputs.release_created }}
      pr_created: ${{ steps.release-please.outputs.prs_created || steps.release-please.outputs.pr_created }}
      pr: ${{ steps.release-please.outputs.pr || '{}' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run release-please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ github.token }}
      - name: Sync App Version
        if: ${{ steps.release-please.outputs.prs_created || steps.release-please.outputs.pr_created }}
        uses: ./.github/release-please-helm-sync-action
        with:
          chart-path: helm/hello-world
          app-path: crates/hello-world
          head-branch: ${{ fromJSON(steps.release-please.outputs.pr || '{}').headBranchName }}
          base-branch: ${{ fromJSON(steps.release-please.outputs.pr || '{}').baseBranchName }}
      # TODO: Force Publish Helm

# github.event.repository.default_branch
