name: Release Please
# Dummy
on:
  push:
    branches:
      - main

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # release-please:
  #   name: Create Release or Bump Version
  #   runs-on: ubuntu-latest
  #
  #   permissions:
  #     pull-requests: write
  #     contents: write
  #
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Release Please with Helm
  #       id: release-please
  #       uses: ./.github/release-please-with-helm-action
  #       with:
  #         chart-path: helm/hello-world
  #         app-path: crates/hello-world
  #
  bump-it:
    name: Release New Version
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: env
      - name: P6M Release
        uses: p6m-actions/p6m-release-action@main
        with:
          language: rust
          enable_helm: 'true'
          helm_chart: helm/hello-world

# github.event.repository.default_branch
